### ISSUE TITLE
Use eslint instead of tslint

### ISSUE THREAD

**Issue by balazsbotond** [balazsbotond/urlcat#54]
We currently use [tslint](https://palantir.github.io/tslint/) for linting but as it turns out, it is deprecated in favor of [eslint](https://eslint.org/).

We need to switch to eslint with a minimal config we can extend later.

Resources:
- [Getting Started](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md)
- [eslint Config](https://eslint.org/docs/user-guide/configuring)
- [eslint Rules](https://eslint.org/docs/rules/)

**Comment by drishit96** [comment]
Hi @balazsbotond, I would like to work on this issue

**Comment by balazsbotond** [comment]
@drishit96 it's yours! :)

**Comment by drishit96** [comment]
I am almost done with the eslint migration, except for this one issue.
`ParamMap` defined [here](https://github.com/balazsbotond/urlcat/blob/12df92ee67f010e8eca58d0156e37bd2739fda53/src/index.ts#L3), has `any` used in it and eslint is giving a warning for the same.
I tried changing it to `string` and the tests were passing locally, but then the tests failed in travis ci because `number` was being used in the test.
Any help?

**Comment by balazsbotond** [comment]
Please disable the warning for that line - we will specify the type more accurately later but this will be OK for now.

**Comment by drishit96** [comment]
I have disabled the warning for that line. Let me know if any other change is needed in the PR.
